Repository chesdenis/net-courses-2019, pull requests merged in 2019-09, with the labels that each got.

#235 Feature/200 trading
  HW3/Seva_Popov/Draw-Game/Draw-Game/GameLogics.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Components/Logger.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Data/TradingSimulatorDbContext.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Dependency/TradingSimulatorRegistry.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/ITradingStart.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Program.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Repositories/AddingSharesToThUserServiceTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Repositories/SharesTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Repositories/TransactionRepositories.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/Repositories/UserTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/TradingSimulation.cs
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/TradingSimulator.ConsoleApp.csproj
  HW6/Seva_Popov/Trading/TradingSimulator.ConsoleApp/TradingStart.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core.Tests/AddingSharesToThUserTest.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core.Tests/SharesServiceTest.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core.Tests/TradingSimulator.Core.Tests.csproj
  HW6/Seva_Popov/Trading/TradingSimulator.Core.Tests/TransactionTests.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core.Tests/UsersServiceTest.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Dto/SharesRegistrationInfo.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Dto/UserRegistrationInfo.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Models/AddingSharesToThUserEntity.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Models/SharesEntity.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Models/TransactionHistoryEntity.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Models/UserEntity.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Repositories/IAddingSharesToThUserServiceTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Repositories/ISharesTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Repositories/ITransactionRepositories.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Repositories/IUserTableRepository.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Services/AddingSharesToThUserService.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Services/SharesService.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Services/TransactionService.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/Services/UserService.cs
  HW6/Seva_Popov/Trading/TradingSimulator.Core/TradingSimulator.Core.csproj
  HW6/Seva_Popov/Trading/TradingSimulator.sln
Labels: Work finished. ReadyForReview, almost done

#259 Complete solution (core, server, client)
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/App.config
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/Client.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/HW7.Client.csproj
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/Program.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/Properties/AssemblyInfo.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Client/Requests.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/App.config
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/BalanceWithStatus.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/ShareToAdd.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/ShareToRemove.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/ShareToUpdate.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/ShareWithPrice.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/TraderToAdd.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/TraderToRemove.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/TraderToupdate.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Dto/TransactionToAdd.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/HW7.Core.csproj
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/IContextProvider.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Models/Portfolio.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Models/Share.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Models/Trader.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Models/Transaction.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Properties/AssemblyInfo.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Repositories/IPortfoliosRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Repositories/ISharesRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Repositories/ITradersRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Repositories/ITransactionsRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Services/SharesService.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Services/TradersService.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/Services/TransactionsService.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/TradingContext.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/TradingContextFactory.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Core/packages.config
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/BalancesController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/ClientsController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/DealController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/SharesController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/TransactionsController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Controllers/ValuesController.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/HW7.Server.csproj
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Program.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Properties/launchSettings.json
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Repositories/PortfoliosRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Repositories/SharesRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Repositories/TradersRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Repositories/TransactionsRepository.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/Startup.cs
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/app.config
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/appsettings.Development.json
  HW7/Аlех_Сhaganоff/HW7/HW7.Server/appsettings.json
  HW7/Аlех_Сhaganоff/HW7/HW7.sln
  HW7/Аlех_Сhaganоff/HW7/appsettings.json
Labels: Work finished. ReadyForReview

#263 Feature/240 trading app
  HW7/Artem_Lozhechkin/Shared/Repositories/CompanyTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/Repositories/ShareTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/Repositories/ShareTypeTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/Repositories/StockTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/Repositories/TraderTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/Repositories/TransactionTableRepository.cs
  HW7/Artem_Lozhechkin/Shared/SeedInitializer.cs
  HW7/Artem_Lozhechkin/Shared/Shared.projitems
  HW7/Artem_Lozhechkin/Shared/Shared.shproj
  HW7/Artem_Lozhechkin/Shared/TradingAppDbContext.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/App.config
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/ConsoleManager.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/Program.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/Properties/AssemblyInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/RequestSender.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/TradingApp.ConsoleTradingManager.csproj
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/TradingManagerRegistry.cs
  HW7/Artem_Lozhechkin/TradingApp.ConsoleTradingManager/packages.config
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/Properties/AssemblyInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/ShareServiceTests.cs
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/TradersServiceTests.cs
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/TradingApp.Core.Tests.csproj
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/TransactionServiceTests.cs
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/app.config
  HW7/Artem_Lozhechkin/TradingApp.Core.Tests/packages.config
  HW7/Artem_Lozhechkin/TradingApp.Core/DTO/ShareInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/DTO/TraderInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/DTO/TransactionInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Logger.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/LoggingServices/LoggingShareService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/LoggingServices/LoggingTraderService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/LoggingServices/LoggingTransactionService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/CompanyEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/ShareEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/ShareTypeEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/StockEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/TraderEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Models/TransactionEntity.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Properties/AssemblyInfo.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Repositories/IRepository.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Services/ShareService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Services/TraderService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/Services/TransactionService.cs
  HW7/Artem_Lozhechkin/TradingApp.Core/TradingApp.Core.csproj
  HW7/Artem_Lozhechkin/TradingApp.Core/app.config
  HW7/Artem_Lozhechkin/TradingApp.Core/packages.config
  HW7/Artem_Lozhechkin/TradingApp.sln
  HW7/Artem_Lozhechkin/WebApi/App.config
  HW7/Artem_Lozhechkin/WebApi/Controllers/BalancesController.cs
  HW7/Artem_Lozhechkin/WebApi/Controllers/ClientsController.cs
  HW7/Artem_Lozhechkin/WebApi/Controllers/ShareController.cs
  HW7/Artem_Lozhechkin/WebApi/Controllers/TransactionController.cs
  HW7/Artem_Lozhechkin/WebApi/Program.cs
  HW7/Artem_Lozhechkin/WebApi/Properties/AssemblyInfo.cs
  HW7/Artem_Lozhechkin/WebApi/TradingApp.WebApi.csproj
  HW7/Artem_Lozhechkin/WebApi/WebApiRegistry.cs
Labels: Work finished. ReadyForReview, almost done, home task

#262 Feature/255 trading simulator web api
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core.Tests/TradingSimulator.Core.Tests.csproj
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core.Tests/UnitTest1.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Dto/SharesRegistrationInfo.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Dto/UserRegistrationInfo.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Models/SharesEntity.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Models/TransactionHistoryEntity.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Models/UserAndSharesEntity.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Models/UserEntity.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Repositories/ISharesTableRepository.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Repositories/ITransactionRepositories.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Repositories/IUserTableRepository.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Services/ISharesService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Services/ITransactionService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Services/IUserAndSharesService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/Services/IUserService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulator.Core/TradingSimulator.Core.csproj
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Data/TradingSimulatorDbContext.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Program.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Repositories/SharesTableRepository.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Repositories/TransactionRepositories.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Repositories/UserTableRepository.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Services/SharesService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Services/TransactionService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/Services/UserService.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/TradingSimulation.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorConsoleApp/TradingSimulatorConsoleApp.csproj
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi.sln
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/HomePageController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/SharesController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/TransactionController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/UserBlackListController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/UserController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Controllers/UserOrangeListController.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Program.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Properties/launchSettings.json
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/Startup.cs
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/TradingSimulatorWebApi.csproj
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/appsettings.Development.json
  HW7/Seva_Popov/TradingSimulatorWebApi/TradingSimulatorWebApi/appsettings.json
Labels: Work finished. ReadyForReview, almost done, home task

#284 Trading Web API by Foxtra
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/App.config
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/ClientRequests.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/Program.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/Properties/AssemblyInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/Simutator.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/packages.config
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Client/stockSimulator.Client.csproj
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/CheckZoneOfClientsTest.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/ClientsServiceTest.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/EditClientsStoksTest.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/Properties/AssemblyInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/TradeServiceTest.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/packages.config
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core.Tests/stockSimulator.Core.Tests.csproj
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/DTO/ClientRegistrationInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/DTO/EditStockOfClientInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/DTO/StockRegistrationInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/DTO/TradeInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Models/ClientEntity.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Models/HistoryEntity.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Models/StockEntity.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Models/StockOfClientsEntity.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Repositories/IClientTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Repositories/IStockOfClientsTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Repositories/IStockTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Repositories/ITransactionHistoryTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Services/ClientService.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Services/EditCleintStockService.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Services/StockService.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/Services/TransactionService.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.Core/stockSimulator.Core.csproj
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Controllers/ClientsController.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Program.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Properties/launchSettings.json
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Repositories/ClientTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Repositories/StockOfClientsTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Repositories/StockTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Repositories/TransactionHistoryTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/SeedData.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/Startup.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/StockSimulatorDbContext.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/appsettings.json
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WebServ/stockSimulator.WebServ.csproj
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/App.config
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Controllers/ClientsController.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Dependecies/StockSimulatorRegistry.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Program.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Properties/AssemblyInfo.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Repositories/ClientTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Repositories/StockOfClientsTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Repositories/StockTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Repositories/TransactionHistoryTableRepository.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/Startup.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/StockInitializer.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/StockSimulatorDbContext.cs
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/packages.config
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulator.WevServer/stockSimulator.WevServer.csproj
  HW7/Sergey_Tkachev/stockSimulatorWeb/stockSimulatorWeb.sln
Labels: home task

#288 Multithread wikipedia links collector
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/App.config
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/ParallelUrlCollector.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/Program.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/Properties/AssemblyInfo.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/Repositories/BaseRepository.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/Repositories/UrlRepository.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/WikiURLCollector.ConsoleApp.csproj
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/WikiUrlDbContext.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/WikiUrlRegistry.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.ConsoleApp/packages.config
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Interfaces/IPageService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Interfaces/IParallelUrlCollectingService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Interfaces/IUrlParsingService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Interfaces/IUrlService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Models/UrlEntity.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Properties/AssemblyInfo.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Repositories/IBaseRepository.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Repositories/IUrlRepository.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Services/PageService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Services/ParallelUrlCollectingService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Services/UrlParsingService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/Services/UrlService.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/WikiURLCollector.Core.csproj
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Core/packages.config
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Properties/AssemblyInfo.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Resources/Emu War - Wikipedia.html
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Tests/PageServiceTests.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Tests/ParallelUrlCollectingServiceTests.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Tests/UrlParsingServiceTests.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/Tests/UrlServiceTests.cs
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/WikiURLCollector.Tests.csproj
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.Tests/packages.config
  HW8/Kirill_Uryvaev/WikiURLCollector/WikiURLCollector.sln
Labels: Work finished. ReadyForReview, home task

#286 Feature/008 get hrefs
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/App.config
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/HW8-EF.csproj
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/LinksContext.cs
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/Models/Links.cs
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/Properties/AssemblyInfo.cs
  HW8/Аlех_Сhaganоff/HW8/HW8-EF/packages.config
  HW8/Аlех_Сhaganоff/HW8/HW8-Tests/HW8-Tests.csproj
  HW8/Аlех_Сhaganоff/HW8/HW8-Tests/HW8Tests.cs
  HW8/Аlех_Сhaganоff/HW8/HW8-Tests/Properties/AssemblyInfo.cs
  HW8/Аlех_Сhaganоff/HW8/HW8-Tests/packages.config
  HW8/Аlех_Сhaganоff/HW8/HW8.sln
  HW8/Аlех_Сhaganоff/HW8/HW8/App.config
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/ConsoleInputProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/ConsoleOutputProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/EFStorageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/LinkProcessorProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/LocalStorageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/PageParserProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/WebClientDownloadPageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/WebClientProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Classes/WebClinetPageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/HW8.csproj
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IClientProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IInputProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/ILinkProcessorProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IOutputProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IPageParserProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IPageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Intefaces/IStorageProvider.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Program.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/Properties/AssemblyInfo.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/WebPageProcessor.cs
  HW8/Аlех_Сhaganоff/HW8/HW8/packages.config
Labels: Work finished. ReadyForReview

#297 Multithread application
  HW8/Mikhail_Romashov/Multithread/Multithread.Core.Tests/LinkServiceTests.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.Core.Tests/Multithread.Core.Tests.csproj
  HW8/Mikhail_Romashov/Multithread/Multithread.Core.Tests/Properties/AssemblyInfo.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.Core.Tests/packages.config
  HW8/Mikhail_Romashov/Multithread/Multithread.Core/Dto/LinkInfo.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.Core/Models/LinkEntity.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.Core/Multithread.Core.csproj
  HW8/Mikhail_Romashov/Multithread/Multithread.Core/Repositories/ILinkTableRepository.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.Core/Services/LinkService.cs
  HW8/Mikhail_Romashov/Multithread/Multithread.sln
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/DataBaseManagerTests.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/HtmlParserTests.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/HtmlReaderTests.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/MultithreadConsoleApp.Tests.csproj
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/Properties/AssemblyInfo.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/Resources/Mummy1998.txt
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp.Tests/packages.config
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/App.config
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Components/DataBaseManager.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Components/FileSystemManager.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Components/HtmlParser.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Components/HtmlReader.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Components/UrlForWork.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Dependencies/MultithreadRegistry.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Dependencies/UrlsStrategyRegistry.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Interfaces/IDataBaseManager.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Interfaces/IFileSystemManager.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Interfaces/IHtmlParser.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Interfaces/IHtmlReader.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/LinksDBContext.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/LinksDbInitializer.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Multithread.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/MultithreadConsoleApp.csproj
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Program.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Properties/AssemblyInfo.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/Repositories/LinkRepository.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/UrlsStrategy/FilmUrls.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/UrlsStrategy/IChooseUrl.cs
  HW8/Mikhail_Romashov/Multithread/MultithreadConsoleApp/packages.config
Labels: Work finished. ReadyForReview, home task

#289 Created multithreading application dor parse wiki pages
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/App.Config
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/DataBaseUW.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/IDataBase.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909031752583_v1.Designer.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909031752583_v1.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909031752583_v1.resx
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909041709268_v2.Designer.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909041709268_v2.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/201909041709268_v2.resx
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Migrations/Configuration.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Model/Links.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/MultithreadApp.DataBase.csproj
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Properties/AssemblyInfo.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Repository.Core/IRepository.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Repository.Core/Repository.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Repository.Interface/ILinksRepository.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/Repository/LinksRepository.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/SiteDbContext.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.DataBase/packages.config
  HW8/Evgeniy_Nikulin/MultithreadApp.Tests/LinksServicesTests.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.Tests/MultithreadApp.Tests.csproj
  HW8/Evgeniy_Nikulin/MultithreadApp.Tests/Properties/AssemblyInfo.cs
  HW8/Evgeniy_Nikulin/MultithreadApp.Tests/app.config
  HW8/Evgeniy_Nikulin/MultithreadApp.Tests/packages.config
  HW8/Evgeniy_Nikulin/MultithreadApp.sln
  HW8/Evgeniy_Nikulin/MultithreadApp/App.config
  HW8/Evgeniy_Nikulin/MultithreadApp/AppRegistry.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Application.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Components/FileProvider.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Components/WikiHttpProvider.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/IApplication.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Interfaces/IFileProvider.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Interfaces/IHttpProvider.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Interfaces/ILinksServices.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/LinksServices.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/MultithreadApp.csproj
  HW8/Evgeniy_Nikulin/MultithreadApp/Program.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/Properties/AssemblyInfo.cs
  HW8/Evgeniy_Nikulin/MultithreadApp/packages.config
Labels: Work finished. ReadyForReview, home task

#299 Feature/280 wiki parser
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/DatasourceManagementServiceTests.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/DownloadingServiceTests.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/HttpMessageHandlerStub.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/PageParsingServiceTests.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/WikipediaParser.Tests.csproj
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.Tests/forTest.html
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser.sln
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/App.config
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/DTO/LinkInfo.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/IUnitOfWork.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Models/LinkEntity.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Program.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Repositories/ILinksTableRepository.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Repositories/LinksTableRepository.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/DatasourceManagementService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/DownloadingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/IDatasourceManagementService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/IDownloadingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/IPageParsingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/IWikipediaParsingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/PageParsingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/Services/WikipediaParsingService.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/UnitOfWork.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/WikiParsingDbContext.cs
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/WikipediaParser.csproj
  HW8/Artem_Lozhechkin/WikipediaParser/WikipediaParser/WikipediaParserRegistry.cs
Labels: Work finished. ReadyForReview, home task

#293 Feature/277 multithread app
  HW8/Svetlana_Koroleva/Links/LinkDBContext/App.config
  HW8/Svetlana_Koroleva/Links/LinkDBContext/DAL/DBInit.cs
  HW8/Svetlana_Koroleva/Links/LinkDBContext/DAL/LinksContext.cs
  HW8/Svetlana_Koroleva/Links/LinkDBContext/LinkDBContext.csproj
  HW8/Svetlana_Koroleva/Links/LinkDBContext/LinkRepository.cs
  HW8/Svetlana_Koroleva/Links/LinkDBContext/Properties/AssemblyInfo.cs
  HW8/Svetlana_Koroleva/Links/LinkDBContext/UnitOfWork.cs
  HW8/Svetlana_Koroleva/Links/LinkDBContext/packages.config
  HW8/Svetlana_Koroleva/Links/Links.sln
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/App.config
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/DownloadWorker.cs
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/LinksParserApp.csproj
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/Program.cs
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/Properties/AssemblyInfo.cs
  HW8/Svetlana_Koroleva/Links/LinksParrserApp/packages.config
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/DownloadServiceTests.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/HTMLPageTest.html
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/LinkServiceTest.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/ParserServiceTests.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/Properties/AssemblyInfo.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/UrlLinksCore.Tests.csproj
  HW8/Svetlana_Koroleva/Links/UrlLinksCore.Tests/packages.config
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/DTO/LinkDTO.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/IService/IDownloadService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/IService/ILinkService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/IService/IParseService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/IUnitOfWork.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Model/Link.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Properties/AssemblyInfo.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Repository/ILinkRepository.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Services/DownloadService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Services/LinkService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/Services/ParserService.cs
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/UrlLinksCore.csproj
  HW8/Svetlana_Koroleva/Links/UrlLinksCore/packages.config
Labels: Work finished. ReadyForReview, almost done

#294 Feature/269 multithread app
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/FileSystemServiceTests.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/PageDownloadServiceTests.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/Properties/AssemblyInfo.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/ReferenceCollector.Core.Tests.csproj
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/Resources/717
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core.Tests/packages.config
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Properties/AssemblyInfo.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/ReferenceCollector.Core.csproj
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Repositories/IFileSystemRepository.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/ConsoleIoDevice.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/FileSystemService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/HtmlParser.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/IFileSystemService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/IIoDevice.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/IPageDownloadService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/Services/PageDownloadService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollector.Core/packages.config
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp.sln
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/App.config
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Context/ReferenceCollectorDbContext.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Dependencies/ReferenceCollectorRegistry.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/IWikiReferenceCollector.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Migrations/Configuration.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Models/ReferenceEntity.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Program.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Properties/AssemblyInfo.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/ReferenceCollectorApp.csproj
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Repositories/FileSystemRepository.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Repositories/IReferenceTable.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Repositories/ReferencesTable.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Services/IReferencesDbService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Services/IWikiReferencesParsingService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Services/ReferencesDbService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/Services/WikiReferencesParsingService.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/WikiReferencesCollector.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorApp/packages.config
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/717
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/Class1.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/Properties/AssemblyInfo.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/ReferenceCollectorApp.Tests.csproj
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/ReferencesDbServiceTests.cs
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/Resources/717
  HW8/Roman-Zuev/ReferenceCollectorApp/ReferenceCollectorAppTests/packages.config
Labels: Work finished. ReadyForReview, home task

#296 Feature/275 multithread app
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Components/ParserPages.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Data/MultithreadDbContext.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Dependency/MultithreadRegistry.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Multithread.ConsoleApp.csproj
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Program.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/Repositories/LinksHistoryRepositoroes.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.ConsoleApp/StartApp.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.Core.Test/LinksHistoryServicesTest.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.Core.Test/Multithread.Core.Test.csproj
  HW8/Seva_Popov/Multithread.Core/Multithread.Core.sln
  HW8/Seva_Popov/Multithread.Core/Multithread.Core/Models/LinksHistoryEntity.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.Core/Multithread.Core.csproj
  HW8/Seva_Popov/Multithread.Core/Multithread.Core/Repositories/ILinksHistoryRepositoroes.cs
  HW8/Seva_Popov/Multithread.Core/Multithread.Core/Services/LinksHistoryServices.cs
Labels: Work finished. ReadyForReview, home task

#295 Multithread app by foxtra
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Models/LinkEntity.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/ICleaner.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/IDownloader.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/ISaver.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/DownloadPageService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/ParsePageService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/SaveIntoDatabaseService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/UrlCollectorService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/SiteParser.Core.csproj
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/App.config
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Dependencies/SiteParserRegistry.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/ISimulator.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Program.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Properties/AssemblyInfo.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/CleanerRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/DownloaderRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/SaverRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Simulator.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/SiteParser.Simulator.csproj
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/SiteParserDbContext.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/dbInitializer.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/packages.config
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/DownloadPageServiceTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/IterationTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/ParsePageServiceTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/Properties/AssemblyInfo.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/Resources/Red_fox.html
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/Resources/test.html
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/SaveIntoDatabaseServiceTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/SiteParser.Tests.csproj
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/packages.config
  HW8/Sergey_Tkachev/SiteParser/SiteParser.sln
Labels: help wanted, home task

#305 I completely forgot to upload this task
  HW5/Beliaev_Pavel/Task/Task.sln
  HW5/Beliaev_Pavel/Task/Task/App.config
  HW5/Beliaev_Pavel/Task/Task/Data/Customer.cs
  HW5/Beliaev_Pavel/Task/Task/Data/Customers.xml
  HW5/Beliaev_Pavel/Task/Task/Data/DataSource.cs
  HW5/Beliaev_Pavel/Task/Task/Data/Order.cs
  HW5/Beliaev_Pavel/Task/Task/Data/Product.cs
  HW5/Beliaev_Pavel/Task/Task/Data/Supplier.cs
  HW5/Beliaev_Pavel/Task/Task/LinqSamples.cs
  HW5/Beliaev_Pavel/Task/Task/LinqToSql.cs
  HW5/Beliaev_Pavel/Task/Task/NorthwindDb.dbml
  HW5/Beliaev_Pavel/Task/Task/NorthwindDb.dbml.layout
  HW5/Beliaev_Pavel/Task/Task/NorthwindDb.designer.cs
  HW5/Beliaev_Pavel/Task/Task/ObjectDumper.cs
  HW5/Beliaev_Pavel/Task/Task/Program.cs
  HW5/Beliaev_Pavel/Task/Task/Properties/AssemblyInfo.cs
  HW5/Beliaev_Pavel/Task/Task/Properties/Resources.Designer.cs
  HW5/Beliaev_Pavel/Task/Task/Properties/Resources.resx
  HW5/Beliaev_Pavel/Task/Task/Properties/Settings.Designer.cs
  HW5/Beliaev_Pavel/Task/Task/Properties/Settings.settings
  HW5/Beliaev_Pavel/Task/Task/SampleForm.Designer.cs
  HW5/Beliaev_Pavel/Task/Task/SampleForm.cs
  HW5/Beliaev_Pavel/Task/Task/SampleForm.resx
  HW5/Beliaev_Pavel/Task/Task/SampleHarness.cs
  HW5/Beliaev_Pavel/Task/Task/Task.csproj
Labels: home task

#303 Feature/282 multithread app
  HW8/Valeriy_Satkov/Multithread App - Issue 282.txt
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/App.config
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/ConnectedLinksDBContext.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/ConnectedLinksParser.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/DependencyInjection/ConnectedLinksRegistry.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/Multithread.ConsoleApp.csproj
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/Program.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/Properties/AssemblyInfo.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/Repositories/LinkTableRepository.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.ConsoleApp/packages.config
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core.Tests/Multithread.Core.Tests.csproj
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core.Tests/ParsingServiceTests.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core.Tests/Properties/AssemblyInfo.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core.Tests/app.config
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core.Tests/packages.config
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Interfaces/IFileManager.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Models/LinkEntity.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Multithread.Core.csproj
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Properties/AssemblyInfo.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Repositories/ILinkTableRepository.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Services/FileManager.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Services/ParsingService.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/Services/ReportsService.cs
  HW8/Valeriy_Satkov/MultithreadApp/Multithread.Core/packages.config
  HW8/Valeriy_Satkov/MultithreadApp/MultithreadApp.sln
  HW8/Valeriy_Satkov/testHTMLContent.txt
Labels: almost done, home task

#307 Feature/281 multithread app by foxtra
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Models/LinkEntity.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/ICleaner.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/IDownloader.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Repositories/ISaver.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/DeleteFileService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/DownloadPageService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/ParsePageService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/SaveIntoDatabaseService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/Services/UrlCollectorService.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Core/SiteParser.Core.csproj
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Dependencies/SiteParserRegistry.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/ISimulator.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Program.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/CleanerRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/DownloaderRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Repositories/SaverRepository.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/Simulator.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/SiteParser.Simulator.csproj
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/SiteParserDbContext.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/dbInitializer.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Simulator/packages.config
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/DownloadPageServiceTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/IterationTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/ParsePageServiceTest.cs
  HW8/Sergey_Tkachev/SiteParser/SiteParser.Tests/SaveIntoDatabaseServiceTest.cs
Labels: enhancement

#315 #302 Created web api with OData protocol support and OData client console app
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/App.config
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/CityClimateService.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/CityService.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/CountryService.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/ODataClientClimate.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/ODataClientClimate.tt
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/ODataClientClimate.ttinclude
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/ODataClientClimateApp.csproj
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/Program.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/Properties/AssemblyInfo.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/metadata.Designer.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/metadata.edmx
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateApp/packages.config
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/App.config
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/ClimateDBContext.csproj
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/DAL/ClimateDBContext.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/DAL/DBInitializer.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/Models/City.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/Models/CityClimateInfo.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/Models/Country.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/Properties/AssemblyInfo.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/ClimateDBContext/packages.config
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData.sln
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/App_Start/BundleConfig.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/App_Start/FilterConfig.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/App_Start/RouteConfig.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/App_Start/WebApiConfig.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/ClimateWebAppWithOData.csproj
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Global.asax
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Global.asax.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/ODataControllers/CitiesController.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/ODataControllers/ClimateInfoController.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/ODataControllers/CountriesController.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/ODataControllers/GenericController.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Properties/AssemblyInfo.cs
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Web.Debug.config
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Web.Release.config
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/Web.config
  HW9/Svetlana_Koroleva/WebAppWithOData/WebAppWithOData/packages.config
Labels: Work finished. ReadyForReview

#317 Updated trading web app
  HW7/Svetlana_Koroleva/TradingWebAPI/SharedContext/Repositories/CommonRepositoty.cs
  HW7/Svetlana_Koroleva/TradingWebAPI/SharedContext/app.config
  HW7/Svetlana_Koroleva/TradingWebAPI/Trading.Core/IServices/IOrdertService.cs
  HW7/Svetlana_Koroleva/TradingWebAPI/Trading.Core/Services/ClientStockService.cs
  HW7/Svetlana_Koroleva/TradingWebAPI/TradingSHWebAPI/Controllers/TransactionsController.cs
  HW7/Svetlana_Koroleva/TradingWebAPI/TradingWebSimulation/App.config
  HW7/Svetlana_Koroleva/TradingWebAPI/TradingWebSimulation/StockExchange.cs
  HW7/Svetlana_Koroleva/TradingWebAPI/TradingWebSimulation/packages.config
Labels: Work finished. ReadyForReview

#311 Feature/196 trading by foxtra
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core.Tests/CheckZoneOfClientsTest.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core.Tests/ClientsServiceTest.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core.Tests/EditClientsStoksTest.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core.Tests/TradeServiceTest.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/DTO/ClientRegistrationInfo.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/DTO/StocksOfClientInfo.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Models/ClientEntity.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Models/HistoryEntity.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Models/StockEntity.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Repositories/IClientTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Repositories/IStockOfClientsTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Repositories/IStockTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Repositories/ITransactionHistoryTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Services/ClientService.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Services/EditCleintStockService.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Services/StockService.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Core/Services/TransactionService.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/App.config
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Dependencies/StockSimulatorRegistry.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Logger.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Program.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Repositories/ClientTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Repositories/StockOfClientsTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Repositories/StockTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Repositories/TransactionHistoryTableRepository.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/Simutator.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/StockInitializer.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/StockSimulatorDbContext.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/UserInterface.cs
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/packages.config
  HW6/Sergey_Tkachev/stockSimulator/stockSimulator.Modulation/stockSimulator.Modulation.csproj
Labels: enhancement

#298 #267 multithread app
  .gitignore
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Class1.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Dto/PageRegistrationInfo.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Models/PageEntity.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/MultithreadApp.Core.csproj
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/PageContextInitializer.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Properties/AssemblyInfo.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Repositories/IDownloadWebPageRepository.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Repositories/IExtractHtmlTags.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Repositories/IPageTableRepository.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Services/PageService.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage.htm
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/a.gif
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/a.htm
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/acc_menu.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/analytics.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/caption.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/colorbox.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/core.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/counter.gif
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/font-awesome.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/hit.gif
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/home_to.png
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/jquery.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/jquery_002.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/jquery_003.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/logo_footer.png
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/mootools-core.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/owl.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/owl.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/owl_002.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/style.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/swiper.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/swiper.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/system.css
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/tag.js
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/top100.jcn
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/TestingWebPage_files/up_to.png
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/Source/XMLFile1.xml
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Core/packages.config
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Test/MultithreadApp.Tests.csproj
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Test/Properties/AssemblyInfo.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Test/Test.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Test/WebPage.xml
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.Test/packages.config
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp.sln
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/App.config
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/ContextInitializer.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Dependencies.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Logger.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/MultithreadApp.csproj
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/MultithreadAppDbContext.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/ParseWebProcess.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Program.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Properties/AssemblyInfo.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Repositories/DownloadWebPageRepository.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Repositories/ExtractHtmlTags.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/Repositories/PageTableRepository.cs
  HW8/Fedusina Daria/MultithreadApp/MultithreadApp/packages.config
Labels: Work finished. ReadyForReview, home task

#324 Finished multithread app
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/App.config
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/App.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/DbInit/MultiAppDbContext.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/DbInit/MultiAppDbInit.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/MultithreadApp.Console.csproj
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/Program.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/Properties/AssemblyInfo.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/Repository/UrlRepository.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/UnitsOfWork/UnitOfWork.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Console/packages.config
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/DownloadServiceTests.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/LinkServiceTest.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/MultithreadApp.Core.Tests.csproj
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/ParsingServiceTests.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/Properties/AssemblyInfo.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/TestHTMLPage.html
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core.Tests/packages.config
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/DTO/UrlInfo.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Model/Url.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/MultithreadApp.Core.csproj
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Properties/AssemblyInfo.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Repository/IUrlRepository.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Services/DownloadService.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Services/ParsingService.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/Services/UrlService.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/UnitsOfWork/IUnitOfWork.cs
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.Core/packages.config
  HW8/Beliaev_Pavel/MultithreadApp/MultithreadApp.sln
Labels: home task
